name: Avg Deal Size
description: null
tableName: fct_sales_pipeline
updatedAt: '2026-03-11T01:05:40.825Z'
metricQuery:
  exploreName: fct_sales_pipeline
  dimensions: []
  metrics:
    - fct_sales_pipeline_avg_deal_size
  filters: {}
  sorts: []
  limit: 1
  metricOverrides: {}
  dimensionOverrides: {}
  tableCalculations: []
  additionalMetrics: []
  customDimensions: []
chartConfig:
  type: big_number
  config:
    label: Avg Deal Size
    style: K
    selectedField: fct_sales_pipeline_avg_deal_size
    showBigNumberLabel: true
slug: avg-deal-size-kpi
tableConfig:
  columnOrder:
    - fct_sales_pipeline_avg_deal_size
spaceSlug: sales-dashboard
version: 1
downloadedAt: '2026-03-11T02:13:31.749Z'
