name: "Migration: Bookings $"
description: null
tableName: opportunity_view
updatedAt: "2026-03-13T19:32:05.040Z"
metricQuery:
  exploreName: opportunity_view
  dimensions:
    - opportunity_view_CloseDate_year
  metrics:
    - opportunity_view_acv_dollars
  filters:
    dimensions:
      id: b5e82681-8d02-4b6c-a642-59454406142f
      and:
        - id: won_filter
          target:
            fieldId: opportunity_view_Won
          values:
            - false
          operator: equals
          required: false
        - id: type_filter
          target:
            fieldId: opportunity_view_Type
          values:
            - Migration
          operator: equals
          required: false
        - id: stage_filter
          target:
            fieldId: opportunity_view_StageName
          values:
            - Closed Won
          operator: equals
          required: false
  sorts:
    - fieldId: opportunity_view_CloseDate_year
      descending: true
  limit: 2
  metricOverrides: {}
  dimensionOverrides: {}
  tableCalculations: []
  additionalMetrics: []
  customDimensions: []
chartConfig:
  type: big_number
  config:
    label: Bookings $
    style: K
    flipColors: false
    selectedField: opportunity_view_acv_dollars
    showComparison: true
    comparisonLabel: vs. prev year
    comparisonFormat: percentage
    showBigNumberLabel: true
    showTableNamesInLabel: true
    conditionalFormattings: []
slug: migration-bookings-acv
tableConfig:
  columnOrder:
    - opportunity_view_CloseDate_year
    - opportunity_view_acv_dollars
spaceSlug: point-of-rental-revops-analytics-demo/revenue/charts-prod
version: 1
downloadedAt: "2026-03-16T12:16:07.364Z"
