name: One Time Revenue
description: null
tableName: opportunity_view
updatedAt: "2026-03-06T19:47:48.701Z"
metricQuery:
  exploreName: opportunity_view
  dimensions:
    - opportunity_view_AccountName
    - opportunity_view_OpportunityName
    - opportunity_view_CloseDate
    - opportunity_view_Owner
    - opportunity_view_Division
    - opportunity_view_Type
    - opportunity_view_ProductFamily
    - opportunity_view_StageName
    - opportunity_view_OppRecordType
    - opportunity_view_BookingPlanOppType2025
    - opportunity_view_Id
  metrics:
    - opportunity_view_hard_imp_value_usd
  filters:
    metrics:
      id: metrics_root
      and:
        - id: hard_imp_positive
          target:
            fieldId: opportunity_view_hard_imp_value_usd
          values:
            - 0
          operator: greaterThan
    dimensions:
      id: root
      and:
        - id: won_filter
          target:
            fieldId: opportunity_view_Won
          values:
            - true
          operator: equals
        - id: stage_filter
          target:
            fieldId: opportunity_view_StageName
          values:
            - Closed Won
          operator: equals
  sorts:
    - fieldId: opportunity_view_hard_imp_value_usd
      descending: true
  limit: 500
  metricOverrides: {}
  dimensionOverrides: {}
  tableCalculations: []
  additionalMetrics: []
  customDimensions: []
chartConfig:
  type: table
  config:
    columns:
      opportunity_view_Id:
        name: Id
      opportunity_view_Type:
        name: Type
      opportunity_view_Owner:
        name: Owner
      opportunity_view_Division:
        name: Division
      opportunity_view_CloseDate:
        name: Close Date
      opportunity_view_StageName:
        name: Stage
      opportunity_view_AccountName:
        name: Account
        frozen: true
      opportunity_view_OppRecordType:
        name: POR / R360
      opportunity_view_ProductFamily:
        name: Product Family
      opportunity_view_OpportunityName:
        name: Opportunity
      opportunity_view_hard_imp_value_usd:
        name: HardImpValue...
      opportunity_view_BookingPlanOppType2025:
        name: BookingPlanOpp...
    hideRowNumbers: false
    showColumnCalculation: true
slug: one-time-revenue
tableConfig:
  columnOrder:
    - opportunity_view_AccountName
    - opportunity_view_OpportunityName
    - opportunity_view_CloseDate
    - opportunity_view_Owner
    - opportunity_view_Division
    - opportunity_view_Type
    - opportunity_view_ProductFamily
    - opportunity_view_StageName
    - opportunity_view_OppRecordType
    - opportunity_view_BookingPlanOppType2025
    - opportunity_view_Id
    - opportunity_view_hard_imp_value_usd
spaceSlug: shared
version: 1
downloadedAt: "2026-03-09T15:49:11.524Z"
