name: Open Pipeline
description: null
tableName: fct_sales_pipeline
updatedAt: "2026-03-04T19:12:31.940Z"
metricQuery:
  exploreName: fct_sales_pipeline
  dimensions: []
  metrics:
    - fct_sales_pipeline_total_open_pipeline
  filters: {}
  sorts: []
  limit: 1
  metricOverrides: {}
  dimensionOverrides: {}
  tableCalculations: []
  additionalMetrics: []
  customDimensions: []
chartConfig:
  type: big_number
  config:
    label: Open Pipeline
    style: K
    selectedField: fct_sales_pipeline_total_open_pipeline
    showBigNumberLabel: true
slug: open-pipeline-kpi
tableConfig:
  columnOrder:
    - fct_sales_pipeline_total_open_pipeline
spaceSlug: sales-dashboard
version: 1
downloadedAt: "2026-03-10T23:30:13.638Z"
