name: Performance by Period
description: 'Booked ACV by close quarter and SDR source for won opportunities.'
tableName: opportunity_view
updatedAt: '2026-03-06T19:35:56.716Z'
metricQuery:
  exploreName: opportunity_view
  dimensions:
    - opportunity_view_CloseDate_quarter
    - opportunity_view_SDRSource
  metrics:
    - opportunity_view_acv_dollars
  filters:
    dimensions:
      id: root
      and:
        - id: won_filter
          target:
            fieldId: opportunity_view_Won
          values:
            - true
          operator: equals
  sorts:
    - fieldId: opportunity_view_CloseDate_quarter
      descending: false
  limit: 500
  metricOverrides: {}
  dimensionOverrides: {}
  tableCalculations: []
  additionalMetrics: []
  customDimensions: []
chartConfig:
  type: cartesian
  config:
    layout:
      stack: false
      xField: opportunity_view_CloseDate_quarter
      yField:
        - opportunity_view_acv_dollars
      flipAxes: false
      showGridY: true
    eChartsConfig:
      xAxis:
        - name: ''
      yAxis:
        - name: ACV $
      legend:
        show: true
      series:
        - type: bar
          label:
            show: true
            position: top
          encode:
            xRef:
              field: opportunity_view_CloseDate_quarter
            yRef:
              field: opportunity_view_acv_dollars
pivotConfig:
  columns:
    - opportunity_view_SDRSource
slug: performance-by-period
tableConfig:
  columnOrder:
    - opportunity_view_CloseDate_quarter
    - opportunity_view_SDRSource
    - opportunity_view_acv_dollars
spaceSlug: shared
version: 1
downloadedAt: '2026-03-09T15:49:11.524Z'
