name: Pipeline by Stage
description: null
tableName: fct_sales_pipeline
updatedAt: "2026-03-11T01:05:57.384Z"
metricQuery:
  exploreName: fct_sales_pipeline
  dimensions:
    - fct_sales_pipeline_stage
  metrics:
    - fct_sales_pipeline_total_pipeline_amount
    - fct_sales_pipeline_opportunity_count
  filters: {}
  sorts:
    - fieldId: fct_sales_pipeline_total_pipeline_amount
      descending: true
  limit: 10
  metricOverrides: {}
  dimensionOverrides: {}
  tableCalculations: []
  additionalMetrics: []
  customDimensions: []
chartConfig:
  type: cartesian
  config:
    layout:
      xField: fct_sales_pipeline_stage
      yField:
        - fct_sales_pipeline_total_pipeline_amount
      flipAxes: true
    eChartsConfig:
      yAxis:
        - name: Amount ($)
      legend:
        show: false
      series:
        - type: bar
          color: "#7262FF"
          encode:
            xRef:
              field: fct_sales_pipeline_stage
            yRef:
              field: fct_sales_pipeline_total_pipeline_amount
          yAxisIndex: 0
slug: pipeline-by-stage
tableConfig:
  columnOrder:
    - fct_sales_pipeline_stage
    - fct_sales_pipeline_total_pipeline_amount
    - fct_sales_pipeline_opportunity_count
spaceSlug: sales-dashboard
version: 1
downloadedAt: "2026-03-11T02:13:31.749Z"
