name: Product Mix
description: null
tableName: opportunity_view
updatedAt: "2026-03-13T19:12:15.820Z"
metricQuery:
  exploreName: opportunity_view
  dimensions:
    - opportunity_view_ProductFamily
  metrics:
    - opportunity_view_acv_dollars
  filters:
    dimensions:
      id: root
      and:
        - id: won_filter
          target:
            fieldId: opportunity_view_Won
          values:
            - true
          operator: equals
  sorts:
    - fieldId: opportunity_view_acv_dollars
      descending: true
  limit: 10
  metricOverrides: {}
  dimensionOverrides: {}
  tableCalculations: []
  additionalMetrics: []
  customDimensions: []
chartConfig:
  type: pie
  config:
    isDonut: true
    metricId: opportunity_view_acv_dollars
    showValue: false
    showLegend: true
    valueLabel: inside
    groupFieldIds:
      - opportunity_view_ProductFamily
    legendPosition: horizontal
    showPercentage: true
    groupSortOverrides: []
    groupColorOverrides:
      Rental Elite: "#FF6A00"
      Rental Essentials: "#a2b3b3"
    groupLabelOverrides: {}
    legendMaxItemLength: 30
    groupValueOptionOverrides: {}
slug: product-mix
tableConfig:
  columnOrder:
    - opportunity_view_ProductFamily
    - opportunity_view_acv_dollars
spaceSlug: point-of-rental-revops-analytics-demo/revenue/charts-prod
version: 1
downloadedAt: "2026-03-16T12:16:07.364Z"
