name: Quarterly Breakdown
description: null
tableName: opportunity_view
updatedAt: "2026-03-06T19:41:02.923Z"
metricQuery:
  exploreName: opportunity_view
  dimensions:
    - opportunity_view_Division
    - opportunity_view_Type
    - opportunity_view_ProductFamily
    - opportunity_view_CloseDate_quarter
  metrics:
    - opportunity_view_acv_dollars
  filters:
    dimensions:
      id: root
      and:
        - id: won_filter
          target:
            fieldId: opportunity_view_Won
          values:
            - true
          operator: equals
  sorts:
    - fieldId: opportunity_view_acv_dollars
      descending: true
  limit: 500
  metricOverrides: {}
  dimensionOverrides: {}
  tableCalculations: []
  additionalMetrics: []
  customDimensions: []
chartConfig:
  type: table
  config:
    columns:
      opportunity_view_Type:
        name: Type
      opportunity_view_Division:
        name: Division
        frozen: true
      opportunity_view_acv_dollars:
        name: ACV
      opportunity_view_ProductFamily:
        name: Product
    showSubtotals: true
    hideRowNumbers: true
    showColumnCalculation: true
pivotConfig:
  columns:
    - opportunity_view_CloseDate_quarter
slug: quarterly-breakdown
tableConfig:
  columnOrder:
    - opportunity_view_Division
    - opportunity_view_Type
    - opportunity_view_ProductFamily
    - opportunity_view_CloseDate_quarter
    - opportunity_view_acv_dollars
spaceSlug: shared
version: 1
downloadedAt: "2026-03-10T23:30:13.638Z"
