name: "Renewal: Bookings $"
description: null
tableName: opportunity_view
updatedAt: "2026-03-10T18:27:41.163Z"
metricQuery:
  exploreName: opportunity_view
  dimensions:
    - opportunity_view_CloseDate_year
  metrics:
    - opportunity_view_acv_dollars
  filters:
    dimensions:
      id: root
      and:
        - id: won_filter
          target:
            fieldId: opportunity_view_Won
          values:
            - true
          operator: equals
        - id: type_filter
          target:
            fieldId: opportunity_view_Type
          values:
            - Renewal
          operator: equals
        - id: acv_positive
          target:
            fieldId: opportunity_view_ACV
          values:
            - 0
          operator: greaterThan
        - id: stage_filter
          target:
            fieldId: opportunity_view_StageName
          values:
            - Closed Won
          operator: equals
        - id: ytd_window
          target:
            fieldId: opportunity_view_IsWithinYTDWindow
          values:
            - true
          operator: equals
  sorts:
    - fieldId: opportunity_view_CloseDate_year
      descending: true
  limit: 2
  metricOverrides: {}
  dimensionOverrides: {}
  tableCalculations: []
  additionalMetrics: []
  customDimensions: []
chartConfig:
  type: big_number
  config:
    label: Bookings $
    style: K
    selectedField: opportunity_view_acv_dollars
    showComparison: true
    comparisonLabel: vs. prev year
    comparisonFormat: percentage
    showBigNumberLabel: true
slug: renewal-bookings-acv
tableConfig:
  columnOrder:
    - opportunity_view_CloseDate_year
    - opportunity_view_acv_dollars
spaceSlug: shared
version: 1
downloadedAt: "2026-03-10T23:30:13.638Z"
