name: 'Scorecard: Migration (Filterable)'
description: >-
  Migration scorecard with dynamic date filtering and support for all dashboard
  filters.
tableName: scorecard_daily
updatedAt: '2026-03-15T22:35:34.189Z'
metricQuery:
  exploreName: scorecard_daily
  dimensions:
    - scorecard_daily_sort_order
    - scorecard_daily_metric_name
  metrics:
    - scorecard_daily_current_period
    - scorecard_daily_previous_period
    - scorecard_daily_pct_change
  filters:
    dimensions:
      id: d0000000-0000-0000-0000-000000000001
      and:
        - id: d0000000-0000-0000-0000-000000000002
          target:
            fieldId: scorecard_daily_category
          values:
            - Migration
          operator: equals
        - id: d0000000-0000-0000-0000-000000000003
          target:
            fieldId: scorecard_daily_report_date
          values:
            - 1
          operator: inTheCurrent
          settings:
            unitOfTime: years
  sorts:
    - fieldId: scorecard_daily_sort_order
      descending: false
  limit: 500
  metricOverrides: {}
  dimensionOverrides: {}
  tableCalculations: []
  additionalMetrics: []
  customDimensions: []
chartConfig:
  type: table
  config:
    columns:
      scorecard_daily_pct_change:
        name: '% Change'
      scorecard_daily_sort_order:
        visible: false
      scorecard_daily_metric_name:
        name: Metric
        frozen: false
      scorecard_daily_current_period:
        name: Current Period
      scorecard_daily_previous_period:
        name: Previous Period
    metricsAsRows: false
    showSubtotals: false
    hideRowNumbers: true
    showTableNames: false
    showResultsTotal: false
    showRowCalculation: false
    showColumnCalculation: false
    conditionalFormattings:
      - color: '#10B981'
        rules:
          - id: positive
            values:
              - +
            operator: startsWith
        target:
          fieldId: scorecard_daily_pct_change
        applyTo: text
      - color: '#EF4444'
        rules:
          - id: negative
            values:
              - '-'
            operator: startsWith
          - id: has_percent
            values:
              - '%'
            operator: include
        target:
          fieldId: scorecard_daily_pct_change
        applyTo: text
slug: scorecard-filterable-migration
tableConfig:
  columnOrder:
    - scorecard_daily_sort_order
    - scorecard_daily_metric_name
    - scorecard_daily_current_period
    - scorecard_daily_previous_period
    - scorecard_daily_pct_change
spaceSlug: point-of-rental-revops-analytics-demo/revenue/charts-prod
version: 1
downloadedAt: '2026-03-16T12:16:07.364Z'
