name: 'Scorecard Secondary: Expansion'
description: null
tableName: scorecard_expansion
updatedAt: '2026-03-10T22:46:08.226Z'
metricQuery:
  exploreName: scorecard_expansion
  dimensions:
    - scorecard_expansion_s
    - scorecard_expansion_Metric
    - scorecard_expansion_Value
    - scorecard_expansion_Prev_YTD
    - scorecard_expansion_Pct_Change
  metrics: []
  filters: {}
  sorts:
    - fieldId: scorecard_expansion_s
      descending: false
  limit: 500
  metricOverrides: {}
  dimensionOverrides: {}
  tableCalculations: []
  additionalMetrics: []
  customDimensions: []
chartConfig:
  type: table
  config:
    columns:
      scorecard_expansion_s:
        visible: false
      scorecard_expansion_Value:
        name: YTD
      scorecard_expansion_Metric:
        name: Metric
        frozen: true
      scorecard_expansion_Prev_YTD:
        name: Prev YTD
      scorecard_expansion_Pct_Change:
        name: '% Change'
    hideRowNumbers: true
    showColumnCalculation: false
    conditionalFormattings:
      - color: '#10B981'
        rules:
          - id: positive
            values:
              - +
            operator: startsWith
        target:
          fieldId: scorecard_expansion_Pct_Change
        applyTo: text
      - color: '#EF4444'
        rules:
          - id: negative
            values:
              - '-'
            operator: startsWith
          - id: has_percent
            values:
              - '%'
            operator: include
        target:
          fieldId: scorecard_expansion_Pct_Change
        applyTo: text
slug: scorecard-table-expansion
tableConfig:
  columnOrder:
    - scorecard_expansion_s
    - scorecard_expansion_Metric
    - scorecard_expansion_Value
    - scorecard_expansion_Prev_YTD
    - scorecard_expansion_Pct_Change
spaceSlug: shared
version: 1
downloadedAt: '2026-03-10T23:37:27.525Z'
