name: SQOs Over Time
description: null
tableName: sqo_daily_cumulative
updatedAt: "2026-03-11T01:06:11.874Z"
metricQuery:
  exploreName: sqo_daily_cumulative
  dimensions:
    - sqo_daily_cumulative_day
  metrics:
    - sqo_daily_cumulative_sqo_running_total
    - sqo_daily_cumulative_sqo_prev_running_total
  filters: {}
  sorts:
    - fieldId: sqo_daily_cumulative_day
      descending: false
  limit: 500
  metricOverrides: {}
  dimensionOverrides: {}
  tableCalculations: []
  additionalMetrics: []
  customDimensions: []
chartConfig:
  type: cartesian
  config:
    layout:
      stack: none
      xField: sqo_daily_cumulative_day
      yField:
        - sqo_daily_cumulative_sqo_running_total
        - sqo_daily_cumulative_sqo_prev_running_total
      flipAxes: false
      showGridY: true
    eChartsConfig:
      xAxis:
        - name: ""
      yAxis:
        - name: SQO Count
      series:
        - name: SQO Count
          type: line
          encode:
            xRef:
              field: sqo_daily_cumulative_day
            yRef:
              field: sqo_daily_cumulative_sqo_running_total
          smooth: true
          yAxisIndex: 0
          isFilteredOut: false
        - name: SQO Count (previous year)
          type: line
          color: "#FF7A00"
          encode:
            xRef:
              field: sqo_daily_cumulative_day
            yRef:
              field: sqo_daily_cumulative_sqo_prev_running_total
          smooth: true
          showSymbol: false
          yAxisIndex: 0
          isFilteredOut: false
      showAxisTicks: false
slug: sqos-over-time
tableConfig:
  columnOrder:
    - sqo_daily_cumulative_day
    - sqo_daily_cumulative_sqo_running_total
    - sqo_daily_cumulative_sqo_prev_running_total
spaceSlug: shared
version: 1
downloadedAt: "2026-03-11T02:13:31.749Z"
