name: SQOs Over Time
description: null
tableName: opportunity_view
updatedAt: "2026-03-06T19:23:34.606Z"
metricQuery:
  exploreName: opportunity_view
  dimensions:
    - opportunity_view_QualifiedDate_day
  metrics:
    - opportunity_view_sqo_count
    - opportunity_view_sqo_count__pop__day_365__j9ryj6
  filters:
    dimensions:
      id: root
      and:
        - id: accepted_filter
          target:
            fieldId: opportunity_view_Accepted
          values:
            - true
          operator: equals
        - id: new_business_filter
          target:
            fieldId: opportunity_view_Type
          values:
            - New Business
          operator: equals
        - id: current_year_filter
          target:
            fieldId: opportunity_view_QualifiedDate_year
          values:
            - "2026"
          operator: equals
  sorts:
    - fieldId: opportunity_view_QualifiedDate_day
      descending: false
  limit: 500
  metricOverrides: {}
  dimensionOverrides: {}
  tableCalculations:
    - name: sqo_running_total
      displayName: SQO Count
      sql: >-
        SUM(${opportunity_view.sqo_count}) OVER (ORDER BY
        ${opportunity_view.QualifiedDate_day} ROWS BETWEEN UNBOUNDED PRECEDING
        AND CURRENT ROW)
      type: number
    - name: sqo_prev_year_running_total
      displayName: SQO Count (previous year)
      sql: >-
        SUM(${opportunity_view.sqo_count__pop__day_365__j9ryj6}) OVER (ORDER BY
        ${opportunity_view.QualifiedDate_day} ROWS BETWEEN UNBOUNDED PRECEDING
        AND CURRENT ROW)
      type: number
  additionalMetrics:
    - name: sqo_count__pop__day_365__j9ryj6
      label: SQO Count (365 days ago)
      hidden: true
      uuid: 57f53f60-11c1-4cc5-ada6-4a621e8db5f4
      sql: ${TABLE}.Id
      table: opportunity_view
      type: count
      generationType: periodOverPeriod
      baseMetricId: opportunity_view_sqo_count
      timeDimensionId: opportunity_view_QualifiedDate_day
      granularity: DAY
      periodOffset: 365
  customDimensions: []
chartConfig:
  type: cartesian
  config:
    layout:
      stack: none
      xField: opportunity_view_QualifiedDate_day
      yField:
        - sqo_running_total
        - sqo_prev_year_running_total
      flipAxes: false
      showGridY: true
    eChartsConfig:
      xAxis:
        - name: ""
      yAxis:
        - name: SQO Count
      series:
        - name: SQO Count
          type: line
          encode:
            xRef:
              field: opportunity_view_QualifiedDate_day
            yRef:
              field: sqo_running_total
          smooth: false
          yAxisIndex: 0
        - name: SQO Count (previous year)
          type: line
          encode:
            xRef:
              field: opportunity_view_QualifiedDate_day
            yRef:
              field: sqo_prev_year_running_total
          smooth: false
          yAxisIndex: 0
slug: sqos-over-time
tableConfig:
  columnOrder:
    - opportunity_view_QualifiedDate_day
    - opportunity_view_sqo_count
    - sqo_running_total
    - opportunity_view_sqo_count__pop__day_365__j9ryj6
    - sqo_prev_year_running_total
spaceSlug: shared
version: 1
downloadedAt: "2026-03-09T14:04:51.104Z"
