name: Total Pipeline
description: null
tableName: fct_sales_pipeline
updatedAt: "2026-03-11T01:06:08.940Z"
metricQuery:
  exploreName: fct_sales_pipeline
  dimensions: []
  metrics:
    - fct_sales_pipeline_total_pipeline_amount
  filters: {}
  sorts: []
  limit: 1
  metricOverrides: {}
  dimensionOverrides: {}
  tableCalculations: []
  additionalMetrics: []
  customDimensions: []
chartConfig:
  type: big_number
  config:
    label: Total Pipeline
    style: K
    selectedField: fct_sales_pipeline_total_pipeline_amount
    showBigNumberLabel: true
slug: total-pipeline-kpi
tableConfig:
  columnOrder:
    - fct_sales_pipeline_total_pipeline_amount
spaceSlug: sales-dashboard
version: 1
downloadedAt: "2026-03-11T02:13:31.749Z"
