name: Won Revenue
description: null
tableName: fct_sales_pipeline
updatedAt: "2026-03-11T01:06:09.719Z"
metricQuery:
  exploreName: fct_sales_pipeline
  dimensions: []
  metrics:
    - fct_sales_pipeline_total_won_revenue
  filters: {}
  sorts: []
  limit: 1
  metricOverrides: {}
  dimensionOverrides: {}
  tableCalculations: []
  additionalMetrics: []
  customDimensions: []
chartConfig:
  type: big_number
  config:
    label: Won Revenue
    style: K
    selectedField: fct_sales_pipeline_total_won_revenue
    showBigNumberLabel: true
slug: won-revenue-kpi
tableConfig:
  columnOrder:
    - fct_sales_pipeline_total_won_revenue
spaceSlug: sales-dashboard
version: 1
downloadedAt: "2026-03-11T02:13:31.749Z"
